broxus/nekoton_repository

- lib/src/models/key_account.dart
- lib/src/models/seed.dart
- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
> feat: seed detail

- lib/src/models/seed.dart
- lib/src/models/seed_list.dart
- lib/src/nekoton_repository.dart
- lib/src/repositories/nekoton_storage_repository/nekoton_storage_repository.dart
- test/src/seeds_list_test.dart
**READY**
- Add seed names as a separate entity
> feat: add seed names to Seed instance

- lib/src/models/seed.dart
- lib/src/models/seed_key.dart
- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
**READY**
- Add missed methods for models
> feat: add rename method to Seed

- lib/src/models/seed.dart
> fix: update props for seed

- lib/src/nekoton_repository.dart
- lib/src/repositories/nekoton_storage_repository/nekoton_storage_repository.dart
**READY**
This PR includes:
* Clear hidden accounts in clearSensitiveData()
* Clear nekoton's keystore and accounts storage directly
> feat: clear nekoton directly

- lib/src/models/account_list.dart
- lib/src/models/address_utils.dart
- lib/src/models/key_account.dart
- lib/src/models/models.dart
- lib/src/models/seed.dart
- lib/src/models/seed_key.dart
- lib/src/models/seed_list.dart
- lib/src/models/transport_strategy.dart
- lib/src/nekoton_repository.dart
- lib/src/repositories/account_repository/account_repository_abstract.dart
- lib/src/repositories/account_repository/account_repository_impl.dart
- lib/src/repositories/nekoton_storage_repository/nekoton_storage_repository.dart
- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
- pubspec.yaml
- test/src/seeds_list_test.dart
**HOLD**
This PR provides breaking changes: now we should use Address and PublicKey dataclasses instead of plain Strings.
> refactor!: add PublicKey and Address dataclasses

- .github/workflows/publish.yaml
- pubspec.yaml
> chore: publish to pubdev

- README.md
- melos.yaml
> chore: update readme

- lib/nekoton_repository.module.dart
- lib/src/models/models.dart
- lib/src/models/token_wallet_related/token_wallet_related.dart
- lib/src/models/token_wallet_related/token_wallet_subscription.dart
- lib/src/nekoton_repository.dart
- lib/src/nekoton_repository_module.dart
- lib/src/repositories/repositories.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_abstract.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/token_wallet_repository/token_wallet_transactions_storage.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- test/src/ton_wallet_repository_test.dart
**READY**
- Added `TokenWalletRepository` (no tests yet)
- Rename test file for `TonWalletRepository`
> feat: add TokenWalletRepository

- lib/src/models/token_wallet_related/token_wallet_ordinary_transaction.dart
- lib/src/models/token_wallet_related/token_wallet_ordinary_transaction.freezed.dart
- lib/src/models/token_wallet_related/token_wallet_related.dart
- lib/src/models/ton_wallet_related/ton_wallet_expired_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_expired_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_ordinary_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_ordinary_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_pending_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_pending_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_related.dart
- lib/src/nekoton_repository.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_abstract.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- pubspec.yaml
> feat: add transactions mapping

- lib/src/repositories/token_wallet_repository/token_wallet_transactions_storage.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_transactions_storage.dart
> fix: change interface to pure class

- lib/src/models/transport_strategy.dart
- lib/src/repositories/transport_repository/transport_repository_impl.dart
> feat: add registering currency after transport update

- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- pubspec.yaml
> feat: update token wallet

- lib/src/models/ton_wallet_related/ton_wallet_expired_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_expired_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_ordinary_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_pending_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_pending_transaction.freezed.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
> feat: update transaction fields

- lib/nekoton_repository.module.dart
- pubspec.yaml
> chore: bumbp bridge

- lib/src/repositories/refresh_polling_queue/cancellable_operation_awaited.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- pubspec.yaml
- test/src/token_wallet_repository_test.dart
- test/src/ton_wallet_repository_test.dart
**READY**
- Bump bridge version
- Update `TonWalletRepository.updateSubscription` and `TokenWalletRepository.updateTokenSubscriptions` as it was started in #44 
- Add tests to `TonWalletRepository` for subscsriptions
- Add tests to `TokenWalletRepository` for subscriptions
> feat: update subscriptions. Add TonWallet test. Add TokenWallet test

- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.freezed.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
> feat: update TonWalletMultisigPendingTransaction

- lib/src/nekoton_repository.dart
- lib/src/repositories/account_repository/account_repository_impl.dart
> feat: update mapping external accounts

- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- lib/src/repositories/transport_repository/transport_repository_abstract.dart
- lib/src/repositories/transport_repository/transport_repository_impl.dart
- pubspec.yaml
- test/src/token_wallet_repository_test.dart
- test/src/ton_wallet_repository_test.dart
**READY**
- Update bridge version
- Replace JRPC to PROTO according to bridge
> feat: update bridge and replace jrpc transport

- lib/src/models/generic_contract/contract_updates_subscription.dart
- lib/src/models/generic_contract/contract_updates_subscription.freezed.dart
- lib/src/models/generic_contract/contract_updates_subscription.g.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
- test/src/generic_contract_repository_test.dart
**READY**
- Added tests for `GenericContractRepository`
- A bit refactored `GenericContractRepository` itself
> feat: add tests for GenerciContractRepository

- lib/src/models/generic_contract/contract_state_changed_event.dart
- lib/src/models/generic_contract/contract_state_changed_event.freezed.dart
- lib/src/models/generic_contract/contract_state_changed_event.g.dart
- lib/src/models/generic_contract/contract_transaction_event.dart
- lib/src/models/generic_contract/contract_transaction_event.freezed.dart
- lib/src/models/generic_contract/contract_transaction_event.g.dart
- lib/src/models/generic_contract/contract_updates_subscription.dart
- lib/src/models/generic_contract/contract_updates_subscription.freezed.dart
- lib/src/models/generic_contract/contract_updates_subscription.g.dart
- lib/src/models/generic_contract/generic_contract.dart
- lib/src/models/generic_contract/generic_contract_subscription_item.dart
- lib/src/models/models.dart
- lib/src/repositories/generic_contract_repository/contract_gql_block_poller.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_abstract.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
- lib/src/repositories/refresh_polling_queue/cancellable_operation_awaited.dart
- lib/src/repositories/repositories.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_gql_block_poller.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- test/src/generic_contract_repository_test.dart
**READY**
- `GenericContractRepository` implementation
> feat: implement GenericContractRepository

- lib/src/repositories/seed_repository/seed_repository_impl.dart
> fix: update adding seed with name

- lib/nekoton_repository.module.dart
- lib/src/nekoton_repository.dart
- lib/src/nekoton_repository_module.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_abstract.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
- test/src/generic_contract_repository_test.dart
> fix: add GenericContract to NekotonRepository

- lib/src/repositories/generic_contract_repository/generic_contract_repository_abstract.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
> feat: add send unawaited version

- pubspec.yaml
> feat: bump bridge version

- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- lib/src/repositories/transport_repository/transport_repository_abstract.dart
- lib/src/repositories/transport_repository/transport_repository_impl.dart
- pubspec.yaml
- test/src/generic_contract_repository_test.dart
- test/src/ton_wallet_repository_test.dart
**READY**
Revert JRPC-related code.
> feat: revert JRPC

- lib/src/repositories/transport_repository/transport_repository_abstract.dart
- lib/src/repositories/transport_repository/transport_repository_impl.dart
- pubspec.yaml
**READY**
Upgrade flutter_nekoton_bridge.
> chore: upgrade flutter_nekoton_bridge

- lib/src/models/seed_list.dart
- lib/src/nekoton_repository.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
> fix: added loading accounts after transport changed

- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
> fix: contract state changed stream

- lib/src/models/seed_list.dart
- lib/src/nekoton_repository.dart
- test/src/seeds_list_test.dart
> fix: add keys sorting by accound id

- lib/src/models/seed.dart
> fix: removing seed name

- lib/src/constants.dart
- lib/src/models/seed.dart
- lib/src/nekoton_repository.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- lib/src/utils/ntp_time.dart
- lib/src/utils/utils.dart
- pubspec.yaml
- test/src/cancelable_operation_test.dart
- test/src/generic_contract_repository_test.dart
- test/src/ton_wallet_repository_test.dart
**READY**
This PR introduces NTP time synchronization for the repository and the FNB.
> feat: ntp time

- lib/src/nekoton_repository.dart
- pubspec.yaml
**READY**
Refactor: updateClockOffset takes Duration instead of int.
> refactor: updateClockOffset takes Duration instead of int

- lib/nekoton_repository.module.dart
- lib/src/models/generic_contract/contract_state_changed_event.freezed.dart
- lib/src/models/generic_contract/contract_state_changed_event.g.dart
- lib/src/models/generic_contract/contract_transaction_event.freezed.dart
- lib/src/models/generic_contract/contract_transaction_event.g.dart
- lib/src/models/generic_contract/contract_updates_subscription.freezed.dart
- lib/src/models/generic_contract/contract_updates_subscription.g.dart
- lib/src/models/token_wallet_related/token_wallet_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/pending_transaction_with_data.freezed.dart
- lib/src/models/ton_wallet_related/pending_transaction_with_data.g.dart
- lib/src/models/ton_wallet_related/ton_wallet_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_pending_transaction.freezed.dart
- lib/src/repositories/repositories.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- pubspec.yaml
**READY**
- Refactored creating subscriptions to reduce general subscribe time
- Now multiple subscriptions may be created at the same time
> fix: allow subscribing multiple tokens at time

- lib/src/models/token_wallet_related/token_wallet_related.dart
- lib/src/models/token_wallet_related/token_wallet_state.dart
- lib/src/models/ton_wallet_related/ton_wallet_related.dart
- lib/src/models/ton_wallet_related/ton_wallet_state.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_abstract.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- test/src/token_wallet_repository_test.dart
- test/src/ton_wallet_repository_test.dart
**READY**
- Updated logic for creating subscriptions for `TonWalletRepository` and `TokenWalletRepository`
- Now creating subscriptions returns `TonWalletState` and `TokenWalletState` that allows tracking real state for creating subscription.
- Added new methods `retrySubscriptions` and `retryTokenSubscription`
> refactor: rework subscription logic, now TonWalletState & TokenWalletState available

- lib/src/repositories/account_repository/account_repository_abstract.dart
- lib/src/repositories/account_repository/account_repository_impl.dart
- pubspec.yaml
- test/src/generic_contract_repository_test.dart
- test/src/ton_wallet_repository_test.dart
> feat: add multiple tokens and update transaction

- lib/src/models/key_account.dart
> fix: methods to account

- lib/src/nekoton_repository.dart
- pubspec.yaml
> feat: add stack to logger

- pubspec.yaml
> fix: bump bridge

- pubspec.yaml
> fix: bumpb bridge

- lib/src/repositories/account_repository/account_repository_impl.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_abstract.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- pubspec.yaml
- test/src/token_wallet_repository_test.dart
- test/src/ton_wallet_repository_test.dart
> fix: transport usage

- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- test/src/ton_wallet_repository_test.dart
> fix: subscribing for external wallets

- lib/nekoton_repository.module.dart
- lib/src/models/account_list.dart
- lib/src/models/generic_contract/contract_state_changed_event.freezed.dart
- lib/src/models/generic_contract/contract_transaction_event.freezed.dart
- lib/src/models/generic_contract/contract_updates_subscription.freezed.dart
- lib/src/models/seed.dart
- lib/src/models/token_wallet_related/token_wallet_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/pending_transaction_with_data.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_expired_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_multisig_pending_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_ordinary_transaction.freezed.dart
- lib/src/models/ton_wallet_related/ton_wallet_pending_transaction.freezed.dart
- lib/src/repositories/account_repository/account_repository_abstract.dart
- lib/src/repositories/account_repository/account_repository_impl.dart
- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
- pubspec.yaml
- test/src/transport_repository_test.dart
> feat: derive key & update dependencies

- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
> feat(EWM-357): optimize `triggerAddingAccounts` method; add progress tracking;

- lib/src/models/token_wallet_related/generic_token_wallet.dart
- lib/src/models/token_wallet_related/jetton_token_wallet.dart
- lib/src/models/token_wallet_related/tip3_token_wallet.dart
- lib/src/models/token_wallet_related/token_wallet_related.dart
- lib/src/models/token_wallet_related/token_wallet_state.dart
- lib/src/models/token_wallet_related/token_wallet_subscription.dart
- lib/src/models/transport_strategy.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/token_wallet_repository/token_wallet_transactions_storage.dart
- pubspec.yaml
- test/src/token_wallet_repository_test.dart
> feat: TON support

- pubspec.yaml
**READY**
Added a new `NotExistingContract` model class that wraps `GenTimings` data to properly handle contract state when a contract doesn't exist. This fixed a JSON parse exception that was occurring with payloads like:
```json
{"type":"notExists","data":{"timings":{"genLt":"0","genUtime":1745257281}}}
```
Previously, the `notExists` state expected direct `GenTimings` objects rather than a wrapper with `data` field, causing parsing failures when processing contract state responses.
> fix(EWM-508): add NotExistingContract model to fix broken contract state

- lib/src/models/generic_contract/contract_not_exists_exception.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- pubspec.yaml
> feat(EWM-508): add explicit exception determines that contract doesn't exists

- lib/src/models/models.dart
- lib/src/models/polling_config.dart
- lib/src/models/transport_strategy.dart
- lib/src/repositories/generic_contract_repository/generic_contract_repository_impl.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_abstract.dart
- lib/src/repositories/token_wallet_repository/token_wallet_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_abstract.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- test/src/generic_contract_repository_test.dart
- test/src/token_wallet_repository_test.dart
- test/src/ton_wallet_repository_test.dart
> feat: add `PollingConfig`

- CHANGELOG.md
- lib/src/models/base/seed_key_base.dart
- lib/src/models/derive_keys_params.dart
- lib/src/models/derive_keys_params.freezed.dart
- lib/src/models/get_public_keys_params.dart
- lib/src/models/get_public_keys_params.freezed.dart
- lib/src/models/models.dart
- lib/src/models/seed.dart
- lib/src/models/seed_key.dart
- lib/src/models/seed_list.dart
- lib/src/models/sign_input_auth.dart
- lib/src/models/sign_input_auth.freezed.dart
- lib/src/nekoton_repository.dart
- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
- lib/src/utils/exceptions.dart
- pubspec.yaml
- test/src/seed_repository_test.dart
> feat: ledger

- lib/src/models/seed_list.dart
- lib/src/repositories/seed_repository/seed_repository_abstract.dart
- lib/src/repositories/seed_repository/seed_repository_impl.dart
- lib/src/repositories/ton_wallet_repository/ton_wallet_repository_impl.dart
- pubspec.yaml
> feat: gasless
